keys:
  - &users '':
      - &phdenzel age10eyh3zd3kusensxuy6j0g82x3qdjguju9r7ryk35zyl67j8w9gxqgx0aqp
  - &hosts '':
      - &idun age1m7y642t548ct35yq4ucspvelclx4efx06se7djff4huk33sved0qvjsrex
      - &phinix age17m4k0g7xn6ek7szh2vg6pdc4vwvvxwfr4zzg36rwhxjfelx6ec7q2v368g
      - &fenrix age1s7pkaz683sf8ms92adh2x4xvspmkfqjenkv06k5leyjly2qewyssnxkwfm
creation_rules:
  - path_regex: hosts/secrets.ya?ml$
    key_groups:
      - age:
          - *phdenzel
          - *idun
          - *phinix
          - *fenrix
  - path_regex: home/phdenzel/secrets.ya?ml$
    key_groups:
      - age:
          - *phdenzel
          - *idun
          - *phinix
          - *fenrix
