{
  pkgs,
  lib,
  ...
}:
with lib; {
  environment.systemPackages = with pkgs; [
    bacon
    binutils
    bun
    cargo-asm
    cargo-license
    cargo-outdated
    cmake
    gdb
    gcc
    gfortran
    gnumake
    gnuplot
    jq
    libgccjit
    pkg-config
    podman
    podman-compose
    python312
    python312Packages.pip
    python312Packages.uv
    python312Packages.virtualenv
    python312Packages.isort
    python312Packages.jedi
    python312Packages.mypy
    python312Packages.python-lsp-server
    python312Packages.rope
    python312Packages.ruff
    rustup
    yq-go
  ];
}
